### PR TITLE
Bump rack-openid to include recent fixes.

### PR DESCRIPTION
**Pull request by Senjai**
Some of them are integral to our application. We have a temporary
version hack running on our local fork at the moment.

See https://github.com/grosser/rack-openid/pull/4 for more discussion.

### CODE REVIEW

**Comment by raphaelcm** [comment]
+1 to this

**Comment by Senjai** [comment]
@raphaelcm I would avoid openid, a lot of providers are moving away from it.

**Comment by raphaelcm** [comment]
@Senjai yeah we support other standards like SAML as well. but we have paying customers that rely on OpenID.

**Comment by Senjai** [comment]
Closing due to inactivity

**Pull request closed without merging**
